; Bulgarian translation for Inno Setup 6 — complete
; ShuNutritionCalc installer

[LangOptions]
LanguageName=<0411><044A><043B><0433><0430><0440><0441><043A><0438>
LanguageID=$0402
LanguageCodePage=1251

[Messages]
SetupAppTitle=Инсталатор
SetupWindowTitle=Инсталиране на %1
UninstallAppTitle=Деинсталиране
UninstallAppFullTitle=Деинсталиране на %1
InformationTitle=Информация
ConfirmTitle=Потвърждение
ErrorTitle=Грешка
SetupLdrStartupMessage=Ще бъде инсталиран %1. Желаете ли да продължите?
LdrCannotCreateTemp=Не може да се създаде временен файл. Инсталацията е прекратена.
LdrCannotExecTemp=Не може да се стартира файл от временната папка. Инсталацията е прекратена.
LastErrorMessage=%1.%n%nГрешка %2: %3
SetupFileMissing=Файлът %1 липсва. Отстранете проблема или се сдобийте с нов пакет.
SetupFileCorrupt=Инсталационните файлове са повредени. Сдобийте се с нов пакет.
SetupFileCorruptOrWrongVer=Инсталационните файлове са повредени или несъвместими с тази версия на инсталатора.
InvalidParameter=Невалиден параметър в командния ред:%n%n%1
SetupAlreadyRunning=Инсталаторът вече се изпълнява.
WinVersionTooLowError=Тази програма изисква %1 версия %2 или по-нова.
WinVersionTooHighError=Тази програма не може да се инсталира на %1 версия %2 или по-нова.
AdminPrivilegesRequired=За инсталирането трябва да сте влезли като администратор.
PowerUserPrivilegesRequired=За инсталирането трябва да сте влезли като администратор или потребител с разширени права.
SetupAppRunningError=Инсталаторът откри, че %1 е стартиран.%n%nЗатворете го и натиснете ОК за да продължите или Отказ за да излезете.
UninstallAppRunningError=Деинсталаторът откри, че %1 е стартиран.%n%nЗатворете го и натиснете ОК за да продължите или Отказ за да излезете.
NotOnThisPlatform=Тази програма не може да се изпълнява на %1.
OnlyOnThisPlatform=Тази програма може да се изпълнява само на %1.
OnlyOnTheseArchitectures=Тази програма може да се инсталира само на:%n%n%1
WindowsServicePackRequired=Тази програма изисква %1 Service Pack %2 или по-нов.
WindowsVersionNotSupported=Тази програма не поддържа вашата версия на Windows.
PrivilegesRequiredOverrideTitle=Изберете начин на инсталиране
PrivilegesRequiredOverrideInstruction=Изберете начин на инсталиране
PrivilegesRequiredOverrideText1=%1 може да се инсталира за всички потребители (изисква администраторски права) или само за вас.
PrivilegesRequiredOverrideText2=%1 може да се инсталира само за вас или за всички потребители (изисква администраторски права).
PrivilegesRequiredOverrideAllUsers=Инсталирай за &всички потребители
PrivilegesRequiredOverrideAllUsersRecommended=Инсталирай за &всички потребители (препоръчително)
PrivilegesRequiredOverrideCurrentUser=Инсталирай само за &мен
PrivilegesRequiredOverrideCurrentUserRecommended=Инсталирай само за &мен (препоръчително)
WelcomeLabel1=Добре дошли в инсталатора на [name]
WelcomeLabel2=Програмата [name/ver] ще бъде инсталирана на вашия компютър.%n%nПрепоръчително е да затворите всички отворени програми преди да продължите.%n%nНатиснете Напред за да продължите.
WizardPassword=Парола
PasswordLabel1=Тази инсталация е защитена с парола.
PasswordLabel3=Въведете паролата и натиснете Напред.
PasswordEditLabel=&Парола:
IncorrectPassword=Неправилна парола. Опитайте отново.
WizardLicense=Лицензионно споразумение
LicenseLabel=Прочетете следната важна информация преди да продължите.
LicenseLabel3=Прочетете споразумението. Трябва да приемете условията за да продължите.
LicenseAccepted=Прие&мам условията
LicenseNotAccepted=&Не приемам условията
WizardInfoBefore=Информация
InfoBeforeLabel=Прочетете следната важна информация преди да продължите.
InfoBeforeClickLabel=Когато сте готови, натиснете Напред.
WizardInfoAfter=Информация
InfoAfterLabel=Прочетете следната информация.
InfoAfterClickLabel=Когато сте готови, натиснете Напред.
WizardUserInfo=Информация за потребителя
UserInfoDesc=Въведете вашите данни.
UserInfoName=&Потребителско име:
UserInfoOrg=&Организация:
UserInfoSerial=&Сериен номер:
UserInfoNameRequired=Трябва да въведете потребителско име.
WizardSelectDir=Избор на папка за инсталация
SelectDirDesc=Където ще бъде инсталирана програмата?
SelectDirLabel3=Програмата ще бъде инсталирана в следната папка.
SelectDirBrowseLabel=За да изберете друга папка, натиснете Преглед.
DiskSpaceGBLabel=Необходимо свободно място: [gb] ГБ
DiskSpaceMBLabel=Необходимо свободно място: [mb] МБ
CannotInstallToNetworkDrive=Инсталацията не може да бъде извършена в мрежов диск.
CannotInstallToUNCPath=Инсталацията не може да бъде извършена в UNC пътека.
InvalidPath=Необходимо е пълна пътека с буква на диск, например:%n%nC:\APP%n%nили UNC пътека:%n%n\\server\share
InvalidDrive=Избраното устройство не съществува или не е достъпно. Изберете друго.
DiskSpaceWarningTitle=Недостатъчно свободно място
DiskSpaceWarning=Инсталацията изисква поне %1 КБ свободно място, но има само %2 КБ.%n%nЖелаете ли да продължите въпреки това?
DirNameTooLong=Наименованието на папката е твърде дълго.
InvalidDirName=Невалидно наименование на папката.
BadDirName32=Наименованието на папката не може да съдържа:%n%n%1
DirExistsTitle=Папката съществува
DirExists=Папката%n%n%1%n%nвече съществува. Инсталирай в нея?
DirDoesntExistTitle=Папката не съществува
DirDoesntExist=Папката%n%n%1%n%nне съществува. Да бъде ли създадена?
WizardSelectComponents=Избор на компоненти
SelectComponentsDesc=Кои компоненти да бъдат инсталирани?
SelectComponentsLabel2=Изберете компонентите за инсталация и натиснете Напред.
FullInstallation=Пълна инсталация
CompactInstallation=Компактна инсталация
CustomInstallation=По избор
NoUninstallWarningTitle=Компоненти намерени
NoUninstallWarning=Намерени са следните компоненти:%n%n%1%n%nПремахването на отметките няма да ги деинсталира.%n%nПродължи?
ComponentSize1=%1 КБ
ComponentSize2=%1 МБ
ComponentsDiskSpaceGBLabel=Необходимо свободно място: [gb] ГБ
ComponentsDiskSpaceMBLabel=Необходимо свободно място: [mb] МБ
WizardSelectTasks=Допълнителни задачи
SelectTasksDesc=Кои допълнителни задачи да бъдат изпълнени?
SelectTasksLabel2=Изберете допълнителни задачи при инсталацията на [name] и натиснете Напред.
WizardSelectProgramGroup=Избор на папка в менюто Старт
SelectStartMenuFolderDesc=Къде да бъдат поставени преките пътища?
SelectStartMenuFolderLabel3=Инсталаторът ще създаде преки пътища в следната папка.
SelectStartMenuFolderBrowseLabel=За друга папка натиснете Преглед.
MustEnterGroupName=Въведете наименование на папката.
GroupNameTooLong=Наименованието е твърде дълго.
InvalidGroupName=Невалидно наименование на папката.
BadGroupName=Наименованието на папката не може да съдържа:%n%n%1
NoProgramGroupCheck2=&Не създавай папка в менюто Старт
WizardReady=Готов за инсталиране
ReadyLabel1=Инсталаторът е готов да инсталира [name].
ReadyLabel2a=Натиснете Инсталирай за да продължите или Назад за да прегледате настройките.
ReadyLabel2b=Натиснете Инсталирай за да продължите.
ReadyMemoUserInfo=Потребителска информация:
ReadyMemoDir=Папка за инсталация:
ReadyMemoType=Тип инсталация:
ReadyMemoComponents=Избрани компоненти:
ReadyMemoGroup=Папка в менюто Старт:
ReadyMemoTasks=Допълнителни задачи:
WizardPreparing=Подготовка за инсталиране
PreparingDesc=Подготовка за инсталиране на [name].
PreviousInstallNotCompleted=Предишната инсталация не е завършена. Рестартирайте компютъра и стартирайте инсталатора отново.
CannotContinue=Инсталацията не може да продължи. Натиснете Отказ за да излезете.
ApplicationsFound=Следните програми използват файлове, които трябва да бъдат обновени. Препоръчително е да ги затворите.
ApplicationsFound2=Следните програми използват файлове, които трябва да бъдат обновени. След инсталацията те ще бъдат рестартирани.
CloseApplications=&Затвори програмите автоматично
DontCloseApplications=&Не затваряй програмите
ErrorCloseApplications=Не успях да затворя всички програми. Затворете ги ръчно преди да продължите.
PrepareToInstallNeedsRestart=Необходимо е рестартиране. След рестартирането стартирайте инсталатора отново.
WizardInstalling=Инсталиране
InstallingLabel=Изчакайте докато [name] бъде инсталиран.
FinishedHeadingLabel=Завършване на инсталацията на [name]
FinishedLabelNoIcons=[name] беше успешно инсталиран на вашия компютър.
FinishedLabel=[name] беше успешно инсталиран. Стартирайте го чрез инсталираните икони.
ClickFinish=Натиснете Завършване за да излезете.
FinishedRestartLabel=За да завърши инсталацията е необходимо рестартиране. Рестартирай сега?
FinishedRestartMessage=За да завърши инсталацията на [name] е необходимо рестартиране.%n%nРестартирай сега?
ShowReadmeCheck=Желая да видя README файла
YesRadio=&Да, рестартирай сега
NoRadio=&Не, ще рестартирам по-късно
RunEntryExec=Стартиране на %1
RunEntryShellExec=Отваряне на %1
ChangeDiskTitle=Необходим е нов диск
SelectDiskLabel2=Поставете диск %1 и натиснете ОК.%n%nАко файловете са другаде, въведете пътеката или натиснете Преглед.
PathLabel=&Пътека:
FileNotInDir2=Файлът "%1" не е намерен в "%2". Поставете правилния диск или изберете друга папка.
SelectDirectoryLabel=Въведете пътеката до диска.
SetupAborted=Инсталацията не беше завършена. Отстранете проблема и стартирайте инсталатора отново.
AbortRetryIgnoreSelectAction=Изберете действие
AbortRetryIgnoreRetry=&Опитайте отново
AbortRetryIgnoreIgnore=&Игнорирайте и продължете
AbortRetryIgnoreCancel=Отменете инсталацията
StatusClosingApplications=Затваряне на програми...
StatusCreateDirs=Създаване на папки...
StatusExtractFiles=Разархивиране на файлове...
StatusCreateIcons=Създаване на преки пътища...
StatusCreateIniEntries=Създаване на INI записи...
StatusCreateRegistryEntries=Създаване на записи в регистъра...
StatusRegisterFiles=Регистриране на файлове...
StatusSavingUninstall=Запазване на информация за деинсталация...
StatusRunProgram=Завършване на инсталацията...
StatusRestartingApplications=Рестартиране на програми...
StatusRollback=Отмяна на промените...
ErrorInternal2=Вътрешна грешка: %1
ErrorFunctionFailedNoCode=%1 е неуспешна
ErrorFunctionFailed=%1 е неуспешна; код %2
ErrorFunctionFailedWithMessage=%1 е неуспешна; код %2.%n%3
ErrorExecutingProgram=Грешка при изпълнение на:%n%1
ErrorRegOpenKey=Грешка при отваряне на ключ в регистъра:%n%1\%2
ErrorRegCreateKey=Грешка при създаване на ключ в регистъра:%n%1\%2
ErrorRegWriteKey=Грешка при запис в регистъра:%n%1\%2
ErrorIniEntry=Грешка при INI запис в "%1".
FileAbortRetryIgnoreSkipNotRecommended=&Пропуснете файла (не се препоръчва)
FileAbortRetryIgnoreIgnoreNotRecommended=&Игнорирайте грешката (не се препоръчва)
SourceIsCorrupted=Изходният файл е повреден
SourceDoesntExist=Изходният файл "%1" не съществува
ExistingFileReadOnly2=Файлът е само за четене и не може да бъде заменен.
ExistingFileReadOnlyRetry=&Премахни защитата и опитай отново
ExistingFileReadOnlyKeepExisting=&Запази съществуващия файл
ErrorReadingExistingDest=Грешка при четене на съществуващия файл:
FileExistsSelectAction=Изберете действие
FileExists2=Файлът вече съществува.
FileExistsOverwriteExisting=&Замени
FileExistsKeepExisting=&Запази съществуващия
FileExistsOverwriteOrKeepAll=&Приложи за всички конфликти
ExistingFileNewerSelectAction=Изберете действие
ExistingFileNewer2=Съществуващият файл е по-нов от инсталирания.
ExistingFileNewerOverwriteExisting=&Замени
ExistingFileNewerKeepExisting=&Запази съществуващия (препоръчително)
ExistingFileNewerOverwriteOrKeepAll=&Приложи за всички конфликти
ErrorChangingAttr=Грешка при промяна на атрибутите:
ErrorCreatingTemp=Грешка при създаване на временен файл:
ErrorReadingSource=Грешка при четене на изходен файл:
ErrorCopying=Грешка при копиране:
ErrorReplacingExistingFile=Грешка при замяна на файл:
ErrorRestartReplace=Грешка RestartReplace:
ErrorRenamingTemp=Грешка при преименуване на временен файл:
ErrorRegisterServer=Регистрацията на DLL/OCX е неуспешна: %1
ErrorRegSvr32Failed=RegSvr32 е неуспешна с код %1
ErrorRegisterTypeLib=Регистрацията на библиотеката е неуспешна: %1
ConfirmUninstall=Сигурни ли сте, че желаете да премахнете напълно [name]?
UninstallOnlyOnWin64=Деинсталацията е възможна само на 64-битова Windows.
OnlyAdminCanUninstall=Деинсталацията е достъпна само за администратори.
UninstallStatusLabel=Изчакайте докато [name] бъде премахнат.
UninstalledAll=[name] беше успешно премахнат.
UninstalledMost=Деинсталацията завърши. Някои елементи не можаха да бъдат премахнати автоматично.
UninstalledAndNeedsRestart=За да завърши деинсталацията е необходимо рестартиране. Рестартирай сега?
UninstallDataCorrupted=Файлът "%1" е повреден. Деинсталацията е невъзможна.
ConfirmDeleteSharedFileTitle=Изтриване на споделен файл?
ConfirmDeleteSharedFile2=Следният файл вече не се използва. Да бъде ли изтрит?%n%nАко е нужен на друга програма, тя може да спре да работи.
SharedFileNameLabel=Файл:
SharedFileLocationLabel=Местоположение:
WizardUninstalling=Деинсталиране
StatusUninstalling=Деинсталиране на %1...
ShutdownBlockReasonInstallingApp=Инсталиране на %1.
ShutdownBlockReasonUninstallingApp=Деинсталиране на %1.
ExitSetupTitle=Изход от инсталатора
ExitSetupMessage=Инсталацията не е завършена.%n%nАко излезете сега, програмата няма да бъде инсталирана.%n%nИзход?
AboutSetupMenuItem=&Относно инсталатора...
AboutSetupTitle=Относно инсталатора
AboutSetupMessage=%1 версия %2%n%n%1 уеб сайт:%n%3
AboutSetupNote=
TranslatorNote=
BeveledLabel=
ButtonBack=< &Назад
ButtonNext=&Напред >
ButtonInstall=&Инсталирай
ButtonOK=ОК
ButtonCancel=Отказ
ButtonYes=&Да
ButtonYesToAll=Да за &всички
ButtonNo=&Не
ButtonNoToAll=Не за в&сички
ButtonFinish=&Завършване
ButtonBrowse=&Преглед...
ButtonWizardBrowse=П&реглед...
ButtonNewFolder=&Нова папка
SelectLanguageTitle=Избор на език
SelectLanguageLabel=Изберете езика за инсталацията.
ClickNext=Натиснете Напред за да продължите или Отказ за да излезете.
BrowseDialogTitle=Избор на папка
BrowseDialogLabel=Изберете папка и натиснете ОК.
NewFolderName=Нова папка
ErrorCreatingDir=Не може да се създаде папката "%1".
ErrorTooManyFilesInDir=Не може да се създаде файл в "%1" — твърде много файлове.
UninstallNotFound=Файлът "%1" не съществува. Деинсталацията е невъзможна.
UninstallOpenError=Файлът "%1" не може да се отвори. Деинсталацията е невъзможна.
UninstallUnsupportedVer=Форматът на "%1" не се разпознава. Деинсталацията е невъзможна.
UninstallUnknownEntry=Непознат запис (%1) в информацията за деинсталация.
UninstallDisplayNameMark=%1 (%2)
UninstallDisplayNameMarks=%1 (%2, %3)
UninstallDisplayNameMark32Bit=32-битова
UninstallDisplayNameMark64Bit=64-битова
UninstallDisplayNameMarkAllUsers=всички потребители
UninstallDisplayNameMarkCurrentUser=текущ потребител
RetryCancelSelectAction=Изберете действие
RetryCancelRetry=&Опитайте отново
RetryCancelCancel=&Отказ
StatusDownloadFiles=Изтегляне на файлове...
DownloadingLabel2=Изтегляне...
ExtractingLabel=Разархивиране...
ButtonStopDownload=&Спри изтеглянето
ButtonStopExtraction=&Спри разархивирането
StopDownload=Спри изтеглянето?
StopExtraction=Спри разархивирането?
ErrorDownloadAborted=Изтеглянето е прекратено.
ErrorDownloadFailed=Неуспешно изтегляне: %1 %2
ErrorDownloadSizeFailed=Неуспешно получаване на размера: %1 %2
ErrorFileSize=Грешен размер. Очакван: %1, получен: %2
ErrorDownloading=Грешка при изтегляне на "%1": %2
ErrorExtracting=Грешка при разархивиране на "%1": %2
ErrorExtractionFailed=Неуспешно разархивиране: %1 %2
ErrorExtractionAborted=Разархивирането е прекратено.
ErrorProgress=Грешка: %1
SourceVerificationFailed=Проверката на файла е неуспешна.
VerificationFileHashIncorrect=Несъответствие на хеш стойността.
VerificationFileNameIncorrect=Несъответствие на името.
VerificationFileSizeIncorrect=Несъответствие на размера.
VerificationFileTagIncorrect=Несъответствие на маркера.
VerificationKeyNotFound=Ключът не е намерен.
VerificationSignatureDoesntExist=Подписът не съществува.
VerificationSignatureInvalid=Подписът е невалиден.
ErrorRestartingComputer=Не мога да рестартирам компютъра. Рестартирайте го ръчно.
ErrorOpeningReadme=Грешка при отваряне на README.
ArchiveIsCorrupted=Архивът е повреден.
ArchiveIncorrectPassword=Неправилна парола за архива.
ArchiveUnsupportedFormat=Неподдържан формат на архива.
